### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by T0oby** [Lucid1ty/Yolov5ForCSGO#1]
run error
ModuleNotFoundError: No module named 'models'
ModuleNotFoundError: No module named 'utils'

**Comment by Lucid1ty** [comment]
Please use pycharm(or other IDE) to open the whole folder and retry

**Comment by Lucid1ty** [comment]
> 

@T0oby 
Please use pycharm(or other IDE) to open the root directory(you will see some file like : aim-csgo),and retry.

**Comment by lly-ke** [comment]
add `import sys
sys.path.append("Project root directory")
` to `main.py `
