### ISSUE TITLE
能否给一份训练图集和标注，万分感谢

### ISSUE THREAD

**Issue by superggh** [Lucid1ty/Yolov5ForCSGO#14]
能否给一份训练图集和标注，万分感谢 superggh@qq.com

**Comment by Lucid1ty** [comment]
@superggh 你可以直接在HuggingFace中搜索你想要的数据集：https://huggingface.co/datasets?sort=trending&search=csgo

![image](https://github.com/Lucid1ty/Yolov5ForCSGO/assets/70336891/048de669-5942-4cc0-984f-6bb86a9581d7)
