### ISSUE TITLE
how to only shoot t or ct?

### ISSUE THREAD

**Issue by cdsisthe1** [Lucid1ty/Yolov5ForCSGO#16]
is there a way to toggle to shoott or ct so it doesnt aim at team?

**Comment by Lucid1ty** [comment]
@cdsisthe1 The model provided by this project is trained with only the head and body labeled, and cannot distinguish between CT and T. If you need to distinguish CT and T, then you can collect the data set yourself for labeling, and then use YOLOv5 for training. After training the model, you also need to modify the targeting code in this project to use it normally.

YOLOv5 model training tutorial: https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/
