### ISSUE TITLE
快速启动报错 

### ISSUE THREAD

**Issue by H4ckBu7eer-EX** [Lucid1ty/Yolov5ForCSGO#2]
C:\Users\yixiang\Downloads\Yolov5ForCSGO>cd aim-csgo

C:\Users\yixiang\Downloads\Yolov5ForCSGO\aim-csgo>python main.py
Traceback (most recent call last):
  File "C:\Users\yixiang\Downloads\Yolov5ForCSGO\aim-csgo\main.py", line 9, in <module>
    from cs_model import load_model
  File "C:\Users\yixiang\Downloads\Yolov5ForCSGO\aim-csgo\cs_model.py", line 8, in <module>
    from models.experimental import attempt_load
ModuleNotFoundError: No module named 'models'

**Comment by Lucid1ty** [comment]
> C:\Users\yixiang\Downloads\Yolov5ForCSGO>cd aim-csgo
> 
> C:\Users\yixiang\Downloads\Yolov5ForCSGO\aim-csgo>python main.py Traceback (most recent call last): File "C:\Users\yixiang\Downloads\Yolov5ForCSGO\aim-csgo\main.py", line 9, in from cs_model import load_model File "C:\Users\yixiang\Downloads\Yolov5ForCSGO\aim-csgo\cs_model.py", line 8, in from models.experimental import attempt_load ModuleNotFoundError: No module named 'models'

1. 下载本仓库 : 点击Code，然后点击Download ZIP。你会得到一个压缩文件。
2. 解压这个压缩文件，你会得到一个名为 : Yolov5ForCSGO-main 的文件夹。
3. 用Pycharm等IDE打开这个文件夹。
4. 再次运行main.py即可。

报错原因 : 没有用Pycharm等IDEA直接打开根目录(在根目录下会有.github和aim-csgo这类文件)
