### ISSUE TITLE
> 您好，我使用的是vscode，用管理员启动，窗口有图标的框出现，鼠标无法移动，

### ISSUE THREAD

**Issue by kkive** [Lucid1ty/Yolov5ForCSGO#8]
> 您好，我使用的是vscode，用管理员启动，窗口有图标的框出现，鼠标无法移动，

看起来是win32api，无法控制鼠标

_Originally posted by @kkive in https://github.com/Lucid1ty/Yolov5ForCSGO/issues/7#issuecomment-1200659948_

**Comment by Lucid1ty** [comment]
@kkive 在不同的设备下确实会导致鼠标控制失效，请尝试修改鼠标控制中的代码，或者使用其他的鼠标控制库\驱动。
